require('dotenv').config()
console.log('JWT_SECRET:', process.env.JWT_SECRET)
const express = require('express')
const cors = require('cors')
const app = express()
app.use(cors())
app.use(express.json())

app.get('/api/health', (req, res) => res.json({ ok: true, servicio: 'GoalKeeperNow API' }))
app.use('/api/auth',           require('./routes/auth'))
app.use('/api/usuarios',       require('./routes/usuarios'))
app.use('/api/porteros',       require('./routes/porteros'))
app.use('/api/solicitudes',    require('./routes/solicitudes'))
app.use('/api/calificaciones', require('./routes/calificaciones'))
app.use('/api/disponibilidad', require('./routes/disponibilidad'))
app.use('/api/productos',      require('./routes/productos'))
app.use('/api/entrenadores',   require('./routes/entrenadores'))
app.use('/api/canchas',        require('./routes/canchas'))
app.use('/api/admin',          require('./routes/admin'))
app.use((req, res) => res.status(404).json({ error: 'Ruta no encontrada.' }))
app.use((err, req, res, next) => { console.error(err); res.status(500).json({ error: 'Error interno del servidor.' }) })

const PORT = process.env.PORT || 3000
app.listen(PORT, () => console.log(`✅ GoalKeeperNow API corriendo en http://localhost:${PORT}`))
